version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /app:/var/www/html
    expose:
     - 80
    environment:
      VIRTUAL_HOST: <domain>
  php:
    build:
      context: .
      dockerfile: PHP.DockerFile
    volumes:
      - /app:/var/www/html
networks:
  mysql:
    external:
      name: mysql
  default:
    external:
      name: nginx-proxy
