#!/bin/sh

DIR="$(dirname "$(readlink -f "$0")")"

# Ensure mysql is up
[ ! "$(docker ps | grep mysql_mysql_1)" ] && docker-compose \
    --project-directory "$DIR/common/mysql" up -d

# Ensure mailhog is up
[ ! "$(docker ps | grep mailhog_mailhog_1)" ] && docker-compose \
    --project-directory "$DIR/common/mailhog" up -d
