#!/bin/sh

DIR="$(dirname "$(readlink -f "$0")")"

# Ensure mysql is up
docker ps | grep -q mysql || docker compose \
    --project-directory "$DIR/common/mysql" up -d

# Ensure mailpit is up
docker ps | grep -q mailpit || docker compose \
    --project-directory "$DIR/common/mailpit" up -d
