services:
  php:
    build:
      context: .
      dockerfile: PHP.DockerFile
    volumes:
      - ./app:/var/www/html
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
     - 80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      VIRTUAL_HOST: <domain>
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - default
      - mysql
      - mailhog
    secrets:
      - user_ssh
networks:
  mailhog:
    external: true
    name: mailhog
  mysql:
    external: true
    name: mysql
  default:
    external: true
    name: nginx-proxy
secrets:
  user_ssh:
    file: ~/.ssh
