version: '3'
services:
  php:
    build:
      context: .
      dockerfile: PHP.DockerFile
    volumes:
      - <project_root>:/var/www/html
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
     - 80
    environment:
      VIRTUAL_HOST: <domain>
networks:
  default:
    external:
      name: nginx-proxy
