version: "3"

services:
   php:
     image: andreccosta/wordpress-xdebug:latest
     volumes:
        - ./app:/var/www/html
     expose:
       - 80
     environment:
       VIRTUAL_HOST: wordpress.local
       XDEBUG_MODE: debug
       XDEBUG_CONFIG: start_with_request=yes discover_client_host=1 log_level=0
     container_name: wordpress
     networks:
       - default
       - mysql
       - mailhog
networks:
  mysql:
    external:
      name: mysql
  default:
    external:
      name: nginx-proxy
  mailhog:
    external:
      name: mailhog
