services:
  php:
    image: andreccosta/wordpress-xdebug:latest
    container_name: "${BUTLER_PROJECT}.${BUTLER_TLD:-test}"
    volumes:
      - ./app:/var/www/html
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "${BUTLER_PROJECT}.${BUTLER_TLD:-test}"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: start_with_request=yes discover_client_host=1 log_level=0
    networks:
      - default
      - mysql
      - mailhog
networks:
  mysql:
    external: true
    name: mysql
  default:
    external: true
    name: nginx-proxy
  mailhog:
    external: true
    name: mailhog
