services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - mailhog
networks:
  mailhog:
    external: true
    name: mailhog

