services:
  php:
    build:
      context: .
      dockerfile: PHP.DockerFile
    container_name: "${BUTLER_PROJECT}"
    volumes:
      - ./app:/var/www/html
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - default
    secrets:
      - user_ssh
networks:
  default:
    external: true
    name: butler
secrets:
  user_ssh:
    file: ~/.ssh
